site_name: Documentations
site_url: https://docs.baissaoui.fr
site_dir: public
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-4 
        name: Switch to dark mode
